CREATE SCHEMA IF NOT EXISTS ops;

CREATE OR REPLACE VIEW ops."用户状态总览" AS
SELECT
  e.as_of_date AS "统计日期",
  u.user_id AS "用户ID",
  u.user_name AS "用户信息",
  u.phone AS "手机号",
  u.channel_raw AS "渠道",
  u.vip_level AS "VIP等级",
  u.distribution_level AS "分销等级",
  u.account_status_raw AS "账户状态",
  u.register_time AS "注册时间",
  u.last_login_time AS "最后登录时间",
  e.last_bet_day AS "最后投注日",
  e.last_recharge_day AS "最后充值成功日",
  e.last_withdraw_day AS "最后提现成功日",
  e.b_gap AS "距最后投注(天)",
  e.r_gap AS "距最后充值(天)",
  e.state_4 AS "用户状态",
  e.lifecycle_tag AS "用户周期标签",
  e.sub_state AS "状态子类",
  e.reason_code AS "衰减情况",
  e.bet_drop AS "投注衰减比",
  e.rech_drop AS "充值衰减比",
  e.wd_rate_short AS "提现比例短窗",
  e.wd_rate_long AS "提现比例长窗",
  e.funding_type AS "资金行为类型",
  e.bonus_rate_rech AS "彩金/充值比(长窗)",
  e.bonus_rate_bet AS "彩金/投注比(长窗)",
  e.p_short AS "盈亏短窗",
  e.p_long AS "盈亏长窗",
  e.profit_reason_tag AS "盈亏原因标签",
  e.pay_fail_rate_short AS "支付失败率短窗",
  e.pay_fail_rate_long AS "支付失败率长窗",
  e.pay_friction_tag AS "支付摩擦标签",
  p.recharge_amt_success AS "当日充值成功金额",
  p.recharge_cnt_success AS "当日充值成功次数",
  p.recharge_cnt_total AS "当日充值总次数",
  p.recharge_cnt_fail AS "当日充值失败次数",
  p.withdraw_amt_success AS "当日提现成功金额",
  p.withdraw_cnt_success AS "当日提现成功次数",
  p.withdraw_cnt_total AS "当日提现总次数",
  p.withdraw_cnt_fail AS "当日提现失败次数",
  p.withdraw_cnt_reject AS "当日提现拒绝次数",
  p.bet_cnt AS "当日投注次数",
  p.bet_amt AS "当日投注金额",
  p.payout AS "当日派彩金额",
  p.profit AS "当日会员盈亏",
  p.bonus_cnt AS "当日彩金次数",
  p.bonus_amt AS "当日彩金金额",
  cr.total_recharge_count AS "总充值成功次数",
  cr.total_recharge_amount AS "总充值成功金额"
FROM mart.user_state_engine e
LEFT JOIN mart.fact_user u ON u.user_id = e.user_id
LEFT JOIN mart.user_profile_daily p ON p.user_id = e.user_id AND p.biz_date = e.as_of_date
LEFT JOIN mart.user_cumulative cr ON cr.user_id = e.user_id;
